name: Set up AWS env

# Controls when the workflow will run
on:

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow contains various steps to setup cloudformation stacks to set up the AWS env
jobs:
 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0-alpha.4
      - name: Install Boto3
        run: python -m pip install --upgrade pip boto3
      - name: Install botocore
        run: python -m pip install --upgrade pip botocore
      # Runs a single command using the runners shell
      
      #Stack for I/O s3 buckets, IAM, etc
      - name: Create IO Stack
        env:
           AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
           AWS_REGION: 'ap-southeast-2'
           FILE_PATH: './Assets/cloudformation/cf_templates/cf_template_stackIO.json'
           STACK_NAME: 'amazon-IO-stack'
        run: python .github/workflows/create_stack.py

      - name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      #Uplopads the required job scripts 
      - name: Upload Job Scripts to s3
        env:
           AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
           AWS_REGION: 'ap-southeast-2'
           FILE_PATH: './Assets/'
           BUCKET_NAME: 'amazon-reviews-assets'
        run: python .github/workflows/upload_job_scripts.py
      
      #create stacks for part 2_1
      - name: Create Common Users Stack
        env:
           AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
           AWS_REGION: 'ap-southeast-2'
           FILE_PATH: './Assets/cloudformation/cf_templates/cf_template_Stackpart21.json'
           STACK_NAME: 'part-2-1-stack'
        run: python .github/workflows/create_stack.py

      #create stacks for part 2_2
      - name: Create Neighbouring Users Stack
        env:
           AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
           AWS_REGION: 'ap-southeast-2'
           FILE_PATH: './Assets/cloudformation/cf_templates/cf_template_Stackpart22.json'
           STACK_NAME: 'part-2-2-stack'
        run: python .github/workflows/create_stack.py

      #create stacks for part 2_3
      - name: Create Negative Users Stack
        env:
           AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
           AWS_REGION: 'ap-southeast-2'
           FILE_PATH: './Assets/cloudformation/cf_templates/cf_template_stackpart23.json'
           STACK_NAME: 'part-2-3-stack'
        run: python .github/workflows/create_stack.py


        #create stacks for step function to run etl jobs
      - name: Create Negative Users Stack
        env:
           AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
           AWS_REGION: 'ap-southeast-2'
           FILE_PATH: './Assets/cloudformation/cf_templates/cf_template_state_machine.json'
           STACK_NAME: 'state-machine-stack'
        run: python .github/workflows/create_stack.py


      
